1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
c = np.random.randint(1, 11, size=(5, 5))
print(c)

[[ 2  5  2  9  5]
 [ 1  3  8  4  9]
 [ 8  2  4  3  2]
 [ 9  5  6 10  3]
 [ 7  8  1  3  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [6]:
d = np.random.random((4, 4))
print(d)

[[0.47878042 0.25882524 0.32236354 0.22590115]
 [0.29111553 0.20050466 0.25909882 0.89101705]
 [0.56195314 0.30282025 0.90752958 0.88100622]
 [0.15505718 0.9048559  0.27324855 0.61201902]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [7]:
e = np.random.randint(1, 10, size=(5,))
f = np.random.randint(1, 10, size=(5,))
print(e, f)
print(e + f)
print(e - f)
print(e * f)
print(e / f)

[4 7 2 8 2] [6 4 9 4 4]
[10 11 11 12  6]
[-2  3 -7  4 -2]
[24 28 18 32  8]
[0.66666667 1.75       0.22222222 2.         0.5       ]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [8]:
g = np.random.rand(7)
h = np.random.rand(7)
gh = np.dot(g, h)
print(g, h, sep='\n')
print(gh)

[0.15455256 0.05993893 0.05281248 0.80314923 0.06065479 0.47522705
 0.18210692]
[0.80148189 0.68216686 0.76429694 0.3250211  0.1189544  0.95975613
 0.61855143]
1.0421240143163675


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [9]:
i = np.random.randint(1, 11, (2, 2), dtype=int)
j = np.random.randint(1, 11, (2, 3), dtype=int)
print(i)
print(j)
print(np.dot(i, j))


[[1 7]
 [9 6]]
[[9 8 9]
 [2 4 5]]
[[ 23  36  44]
 [ 93  96 111]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [10]:
k = np.random.randint(1, 11, (3,3))
k_inv =np.linalg.inv(k)
print(k)
print(k_inv)

[[10  4  7]
 [ 4  1  6]
 [10  2 10]]
[[-0.04347826 -0.56521739  0.36956522]
 [ 0.43478261  0.65217391 -0.69565217]
 [-0.04347826  0.43478261 -0.13043478]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [11]:
l = np.random.random((4, 4))
l_transp = l.T
print(l)
print(l_transp) 

[[0.6581496  0.68065334 0.58445385 0.17812452]
 [0.20037567 0.26297751 0.7072037  0.66415913]
 [0.93519778 0.50538268 0.16575032 0.20254749]
 [0.50712839 0.47465859 0.12974236 0.73188113]]
[[0.6581496  0.20037567 0.93519778 0.50712839]
 [0.68065334 0.26297751 0.50538268 0.47465859]
 [0.58445385 0.7072037  0.16575032 0.12974236]
 [0.17812452 0.66415913 0.20254749 0.73188113]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [12]:
m = np.random.randint(1, 11, size=(3, 4))
n =np.random.randint(1, 11, 4)

print(m)
print(n)
print(np.dot(m,n))

[[10  4  6  8]
 [ 8  8  1  4]
 [ 5  5  5  3]]
[ 5  2  6 10]
[174 102  95]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [13]:
o = np.random.random((2,3))
p =np.random.random(3)

print(o)
print(p)
print(np.dot(o,p))

[[0.95497814 0.38744394 0.25194535]
 [0.19004211 0.58767905 0.93612425]]
[0.82510376 0.43648787 0.16178115]
[0.99783065 0.5647665 ]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [14]:
q = np.random.randint(1, 11, (2, 2))
r = np.random.randint(1, 11, (2, 2))
qr = np.multiply(q, r)
print(q, r, qr, sep='\n')

[[9 5]
 [7 4]]
[[10  9]
 [ 5  3]]
[[90 45]
 [35 12]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [15]:
s = np.random.randint(1, 11, (2, 2))
t = np.random.randint(1, 11, (2, 2))
st = np.dot(s, t)
print(s, t, st, sep='\n')

[[2 4]
 [5 1]]
[[4 3]
 [3 5]]
[[20 26]
 [23 20]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [16]:
u = np.random.randint(1, 101, (5, 5))
print(u, u.sum(), sep='\n')

[[  2  39  76  62  90]
 [ 78  56  12  19   3]
 [ 99  30  26  22   8]
 [ 81  36  54  76   8]
 [ 30  56  53 100  85]]
1201


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [17]:
v1 = np.random.randint(1, 11, (4, 4))
v2 = np.random.randint(1, 11, (4, 4))
v1_sub_v2 = np.subtract(v1, v2)
print(v1, v2, v1-v2, v1_sub_v2, sep='\n')

[[ 8  9  5 10]
 [ 5  8  8  2]
 [ 5  2  7  9]
 [ 4  1  1  4]]
[[9 3 9 4]
 [1 1 9 2]
 [8 8 2 9]
 [1 8 1 8]]
[[-1  6 -4  6]
 [ 4  7 -1  0]
 [-3 -6  5  0]
 [ 3 -7  0 -4]]
[[-1  6 -4  6]
 [ 4  7 -1  0]
 [-3 -6  5  0]
 [ 3 -7  0 -4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [18]:
x = np.random.random((3, 3))
x_vector = np.array([el.sum() for el in x])
print(x)
print(x_vector)
# або так:
row_sums_vector = np.sum(x, axis=1, keepdims=True)
print(row_sums_vector)

[[0.17865449 0.81825034 0.09252149]
 [0.00242953 0.04903267 0.77289572]
 [0.4864989  0.99292611 0.86033641]]
[1.08942632 0.82435792 2.33976142]
[[1.08942632]
 [0.82435792]
 [2.33976142]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [19]:
y = np.random.randint(1, 1001, (3, 4))
y_sqr = np.square(y)
print(y, y_sqr, sep='\n')


[[666 740 473   7]
 [180 927 422 634]
 [476 373 765 741]]
[[443556 547600 223729     49]
 [ 32400 859329 178084 401956]
 [226576 139129 585225 549081]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [20]:
z = np.random.randint(1, 51, size=4)
z_sqrt = np.sqrt(z)
print(z, z_sqrt, sep='\n')

[27 48 28 29]
[5.19615242 6.92820323 5.29150262 5.38516481]
